# Generated by Django 2.0.2 on 2019-05-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('album', models.CharField(max_length=80)),
                ('artist', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=10)),
                ('link', models.TextField()),
            ],
        ),
    ]
