# Generated by Django 2.0.2 on 2019-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicCacheItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('artist', models.CharField(max_length=80)),
                ('album', models.CharField(max_length=80)),
                ('length', models.CharField(max_length=10)),
                ('filename', models.TextField()),
            ],
        ),
    ]
