# Generated by Django 2.2.1 on 2019-05-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0002_musiccacheitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='playing',
            field=models.BooleanField(default=False),
        ),
    ]
